micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
erp-itau.host: http://localhost:9091/api/v1/
bcb.host: http://localhost:8082/api/v1/pix/keys
